# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-16 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=b'', null=True)),
                ('state', models.CharField(choices=[(b'LAUNCHED', b'Launched'), (b'FAILED', b'Failed'), (b'KILLED', b'Killed'), (b'ACTIVATED', b'Activated'), (b'DEACTIVATED', b'Deactivated'), (b'REBALANCED', b'Rebalanced')], max_length=10)),
                ('acked', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.BatchQuery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchJobHistoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=b'', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.BatchJobHistory')),
            ],
        ),
        migrations.CreateModel(
            name='StreamingJobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=b'', null=True)),
                ('state', models.CharField(choices=[(b'LAUNCHED', b'Launched'), (b'FAILED', b'Failed'), (b'KILLED', b'Killed'), (b'ACTIVATED', b'Activated'), (b'DEACTIVATED', b'Deactivated'), (b'REBALANCED', b'Rebalanced')], max_length=10)),
                ('acked', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.RealtimeQuery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingJobHistoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=b'', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.StreamingJobHistory')),
            ],
        ),
    ]
