# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-16 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('md_file', models.CharField(max_length=200)),
                ('command', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('bolt_name', models.CharField(default=b'', max_length=100)),
                ('node_type', models.CharField(choices=[(b'SOURCE', b'Source'), (b'SINK', b'Sink'), (b'JOIN', b'Join'), (b'NORMAL', b'Normal'), (b'NA', b'Na')], default=b'NORMAL', max_length=6)),
                ('storm_node_type', models.CharField(choices=[(b'BOLT', b'Bolt'), (b'SPOUT', b'Spout')], default=b'BOLT', max_length=5)),
                ('category', models.ForeignKey(default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='help.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('field_name', models.CharField(default=b'', max_length=200)),
                ('default_value', models.CharField(blank=True, default=b'', max_length=100, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('placeholder', models.CharField(default=b'', max_length=100)),
                ('command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='help.Command')),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('field_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('has_options', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JarFile',
            fields=[
                ('jar_file', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('package_location', models.CharField(default=b'', max_length=200)),
                ('package_filename', models.CharField(default=b'', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('library_type', models.CharField(choices=[(b'BASE_LIBRARY', b'Base Library'), (b'THIRD_PARTY_LIBRARY', b'Third Party Library')], default=b'BASE_LIBRARY', max_length=6)),
                ('description', models.TextField(default=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('option_value', models.CharField(max_length=200)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='help.Field')),
            ],
        ),
        migrations.CreateModel(
            name='RegistryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.CharField(max_length=50)),
                ('package_location', models.CharField(default=b'', max_length=200)),
                ('package_filename', models.CharField(default=b'', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jarfile',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.Library'),
        ),
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='help.FieldType'),
        ),
        migrations.AddField(
            model_name='category',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.Library'),
        ),
    ]
